### ISSUE TITLE
Google Chat Desktop

### ISSUE THREAD

**Issue by kravchenko-a** [zviryatko/google-bard-desktop#1]
Hello!
Thanks for the Google Bard Desktop.
Can you make the same but for the Google Chat please: https://chat.google.com/

**Comment by zviryatko** [comment]
Yep, it should not be hard 👌

**Comment by kravchenko-a** [comment]
Hello @zviryatko
Can you tell please when you will have a time to do this?

**Comment by zviryatko** [comment]
Already checked, I didn't find any workable electron wrapper around Google chat. I tried the most popular one from github, but it's archived and doesn't work well for me (can't even build). I'm not experienced in building electron wrappers, but if I do not find a workable one, I will be required to build by myself.

**Comment by zviryatko** [comment]
@modder2 I've finally make electron works locally :roll_eyes:. Typescript and js are not my superpowers.

**Comment by zviryatko** [comment]
@modder2 here is the update https://github.com/zviryatko/google-chat-electron 
Restored electron version, at least tested on linux with latest stable node. It requires some work, but I just cut everything that doesn't work well, like osx support :rofl: 
Now waiting for snapcraft.io approves my app name.

**Comment by zviryatko** [comment]
@modder2 still waiting for approval for name, but you can try snap package https://github.com/zviryatko/google-chat-electron/releases/tag/3.0.0

**Comment by kravchenko-a** [comment]
@zviryatko Thanks for the research.
Thanks to you, I've seen on this readme page https://github.com/ankurk91/google-chat-electron that Google Chat and other Google services can be installed via Chrome as independent PWA applications :grin:
https://support.google.com/chat/answer/10194711

**Comment by zviryatko** [comment]
yes, but you won't have support for Tray icon :smirk:

**Comment by zviryatko** [comment]
@modder2 it's published https://snapcraft.io/google-chat-desktop
there is still issue during login with "browser not secure", but the previous developer left a workaround in Help/Troubleshoot menu.
If it still makes sense, you can use it.

**Comment by kravchenko-a** [comment]
@zviryatko Thank you very much!
